### ISSUE TITLE
Add descriptions to action.yml inputs

### ISSUE THREAD

**Issue by Andrew-Kulpa** [Andrew-Kulpa/create-release#2]
#### Description
`action.yml` inputs need descriptions for usage to be clearer.

#### Files
`action.yml`

#### Tasks

- [ ] Describe tag
- [ ] Describe name
- [ ] Describe body
- [ ] Describe prerelease (boolean)
- [ ] Describe overwrite (boolean)
- [ ] Describe artifacts (new-line delimited files)
- [ ] Describe artifact (a single file)

**Comment by zohra009** [comment]
im on it !
