### ISSUE TITLE
Add support for body message of release from a file

### ISSUE THREAD

**Issue by Andrew-Kulpa** [Andrew-Kulpa/create-release#4]
#### Description
Some projects accumulate or generate a changelog for their releases. In order for these projects to use this action, they would need support for generating a body message from a previously generated file. This could be done by adding an additional input called `bodyFile` that takes in any text file and inserts it the body message.

#### Files
  - `./src/main/main.ts`
  - `action.yml`
  - `README.md`

#### Tasks

- [ ] Extend `main.ts` to support a source file for the body message
- [ ] Update`action.yml` with the new related input and a description
- [ ] Update the README accordingly

**Comment by bartius-nigel** [comment]
Hi Andrew,

Thanks for the well written issue! 

Can you please clarify quickly so I don't spin my wheels. My understanding is that you want the function `createRelease()` extended to include a filepath called `bodyFile` and the contents of that file added to the `body` input. Is that correct?

**Comment by Andrew-Kulpa** [comment]
@bartius-nigel yes that should work! I honestly should pull the tag/name handling into its own function too just to clean up `run()` some more.

**Comment by bartius-nigel** [comment]
Awesome, I'm on it! Is there also an example of the file format for the `bodyFile`?
