### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by Andrew-Kulpa** [Andrew-Kulpa/create-release#5]
#### Description
This project initially worked, but to assure future changes maintain current functionality we need to add some tests for each of the inputs.

#### Tasks

- [ ] Add test for tag
- [ ] Add test for name
- [ ] Add test for body
- [ ] Add test for prerelease
- [ ] Add test for overwrite
- [ ] Add test for artifacts
